CREATE TABLE STUDENT
(SSN CHAR(9) NOT NULL,
STUDENTNAME VARCHAR(30) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PRIMARY KEY(SSN)	
);

CREATE TABLE TA
(SSN CHAR(9) NOT NULL,
SALARY CHAR(20) NOT NULL,
PRIMARY KEY(SSN),
FOREIGN KEY(SSN) REFERENCES STUDENT(SSN)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE INSTRUCTOR
(TITLE VARCHAR(50) NOT NULL,
INSTRUCTORID CHAR(9) NOT NULL,
INSTRUCTORNAME VARCHAR(50) NOT NULL,
PRIMARY KEY(INSTRUCTORID)
);

CREATE TABLE CLASSROOM
(ROOMNO CHAR(5) NOT NULL,
BUILDING VARCHAR(20) NOT NULL,
CAPACITY CHAR(5) NOT NULL,
PRIMARY KEY(ROOMNO, BUILDING)
);

CREATE TABLE COURSE
(COURSENO CHAR(12) NOT NULL,
COURSENAME VARCHAR(40) NOT NULL,
NOOFSTUDENTS INT NOT NULL,
INSTRUCTORID CHAR(9) NOT NULL,
TASSN CHAR(9) NOT NULL,
PRIMARY KEY(COURSENO),
FOREIGN KEY(INSTRUCTORID) REFERENCES INSTRUCTOR(INSTRUCTORID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(TASSN) REFERENCES TA(SSN)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE ENROLLED
(SSN CHAR(9) NOT NULL,
COURSENO CHAR(12) NOT NULL,
GRADE CHAR(2) NOT NULL,
PRIMARY KEY(SSN, COURSENO),
FOREIGN KEY(SSN) REFERENCES STUDENT(SSN)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(COURSENO) REFERENCES COURSE(COURSENO)
ON DELETE CASCADE
ON UPDATE CASCADE
);


CREATE TABLE ONLINECOURSE
(COURSENO CHAR(12) NOT NULL,
URL VARCHAR(100) NOT NULL,
PRIMARY KEY(COURSENO),
FOREIGN KEY(COURSENO) REFERENCES COURSE(COURSENO)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE TRADITIONALCOURSE
(COURSENO CHAR(12) NOT NULL,
ROOMNO CHAR(5) NOT NULL,
BUILDING VARCHAR(20) NOT NULL,
CLASSTIME CHAR(7) NOT NULL,
PRIMARY KEY(COURSENO),
FOREIGN KEY(ROOMNO, BUILDING) REFERENCES CLASSROOM(ROOMNO, BUILDING)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(COURSENO) REFERENCES COURSE(COURSENO)
ON DELETE CASCADE
ON UPDATE CASCADE
);


CREATE VIEW TAVIEW AS
SELECT S.SSN, S.STUDENTNAME, S.ADDRESS, S.EMAIL, T.SALARY
FROM STUDENT AS S, TA AS T
WHERE S.SSN = T.SSN;

CREATE VIEW ONLINECOURSEVIEW AS
SELECT C.COURSENO, C.COURSENAME, C.INSTRUCTORID, C.NOOFSTUDENTS, C.TASSN, W.URL
FROM COURSE AS C, ONLINECOURSE AS W
WHERE C.COURSENO = W.COURSENO;

CREATE VIEW TRADITIONALCOURSEVIEW AS
SELECT C.COURSENO, C.COURSENAME, C.INSTRUCTORID, C.NOOFSTUDENTS, C.TASSN, T.CLASSTIME, T.ROOMNO, T.BUILDING
FROM COURSE AS C, TRADITIONALCOURSE AS T
WHERE C.COURSENO = T.COURSENO;