DROP VIEW TRADITIONALCOURSEVIEW;
DROP VIEW ONLINECOURSEVIEW;
DROP VIEW TAVIEW;
DROP VIEW TA_COURSE;
DROP VIEW STUDENT_GRADE_A;
DROP FUNCTION COURSE_INSTRUCTOR;
DROP PROCEDURE GET_TA;
DROP PROCEDURE GETSTUDENTCOURSE;
DROP TRIGGER IF EXISTS INC_ENROLLMENT_NUMBER;
DROP TRIGGER IF EXISTS DEL_ENROLLMENT_NUMBER;
DROP TABLE TRADITIONALCOURSE;
DROP TABLE ONLINECOURSE;
DROP TABLE ENROLLED;
DROP TABLE COURSE;
DROP TABLE CLASSROOM;
DROP TABLE INSTRUCTOR;
DROP TABLE TA;
DROP TABLE STUDENT;


